{% set name = "lovely-jax" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lovely-jax-{{ version }}.tar.gz
  sha256: 43b1c44bf072de3a878873fcd041dd309f44974f6cca158dffb823e563297d1a

build:
  noarch: python
  number: 0
  # The script can have multiple lines. Hence, keep it at the end.
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jax
    - lovely-numpy >=0.2.8

test:
  imports:
    - lovely_jax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xl0/lovely-jax
  summary: 💘 Lovely JAX
  license: MIT
  license_file: LICENSE
  description: |2

    PyPI: [https://pypi.org/project/lovely-jax/](https://pypi.org/project/lovely-jax/)

  dev_url: https://github.com/xl0/lovely-jax
  doc_url: https://xl0.github.io/lovely-jax/

extra:
  recipe-maintainers:
    - sugatoray
    - xl0
